language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf texinfo libtiff-dev
before_script:
  - cd ..
  - git clone http://git.sv.gnu.org/r/autoconf.git
  - cd autoconf
  - aclocal -I m4
  - automake -a
  - autoconf
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd ..
  - git clone https://github.com/ImageMagick/ImageMagick
  - cd ImageMagick
  - git checkout ImageMagick-6
  - ./configure --prefix=/usr
  - make -j4
  - which clang
  - sudo make install
  - cd ..
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-mrmagick/.travis_build_config.rb build_config.rb
script:
  - make all test
