language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y --reinstall install autoconf
  - git clone https://github.com/ImageMagick/ImageMagick
  - cd ImageMagick
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd ..
install:
    - sudo apt-get -qq install rake bison git gperf libmagick++-dev libossp-uuid-dev
before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-mrmagick/.travis_build_config.rb build_config.rb
script:
  - make all test
