language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install texinfo
  - cd ..
  - git clone http://git.sv.gnu.org/r/autoconf.git
  - cd autoconf
  - ls
  - aclocal -I m4
  - automake -a
  - autoconf
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd ..
  - git clone https://github.com/ImageMagick/ImageMagick
  - cd ImageMagick
  - ./configure --prefix=/usr
  - make -j4
  - sudo make install
  - cd ..
install:
    - sudo apt-get -qq install rake bison git gperf libmagick++-dev libossp-uuid-dev
before_script:
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-mrmagick/.travis_build_config.rb build_config.rb
script:
  - make all test
